/* eslint-disable @next/next/no-sync-scripts */
"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSideBar from "./_components/sidebar";
import LightRays from "@/components/LightRays";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://t.contentsquare.net/uxa/6c6ab6f0a64d7.js"></script>
        <meta name="google-site-verification" content="DTjnT0AFssM6Ek-3HwXDdJIL_zrpni03KOi0gi7cOOg" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
        <div className="fixed inset-0 -z-10">
          <LightRays
            raysOrigin="top-center"
            raysColor="#00ffff"
            raysSpeed={1}
            lightSpread={90.8}
            rayLength={3.2}
            followMouse={true}
            mouseInfluence={0.1}
            noiseAmount={0.1}
            distortion={0}
            className="custom-rays"
          />
        </div>
        <SidebarProvider>
          <AppSideBar />
          <main className="relative min-h-screen w-screen">
            <div className="mb-[8vh]">
              <Navbar />
            </div>
            <SidebarTrigger />
              {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
