"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSideBar from "./_components/sidebar";
import FloatingLines from "@/components/FloatingLines";
import Prism from "@/components/Prism";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
        <div className="fixed inset-0 -z-10">
          <Prism

            animationType="rotate"

            timeScale={0.5}

            height={3.5}

            baseWidth={5.5}

            scale={3.6}

            hueShift={0}

            colorFrequency={1}

            noise={0}

            glow={1}

          />
        </div>

        <SidebarProvider>
          <AppSideBar />
          <main className="relative min-h-screen w-screen">
            <SidebarTrigger />
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
